# ==================
# hugoalh's Repository Resource - Mergify
#   Language:
#     YAML
#   Last Update:
#     2020-11-28
#   Schema:
#     https://docs.mergify.io/configuration.html
# ==================
pull_request_rules:
  - name: "Automatically merge dependency update once confirmed"
    conditions:
      - "-closed"
      - "-conflict"
      - "-draft"
      - "label=confirmed✔"
      - "label=dependency📦"
      - "-merged"
    actions:
      merge:
        method: "squash"
        strict: false
        commit_message: "default"
