var advancedDetermine = require("@hugoalh/advanced-determine");
console.log(advancedDetermine.areEqual("Test", "test"));
console.log(advancedDetermine.areEqual([10, 20, 30, 40], [10, 20, 30, 40]));
console.log(advancedDetermine.areEqual([10, [20], 30, 40], [10, 20, 30, 40]));
console.log(advancedDetermine.areEqual(1, "1"));
console.log(advancedDetermine.isArray([], { empty: false }));
console.log(advancedDetermine.isArray([]));
console.log(advancedDetermine.isArray([1, 2, 3]));
console.log(advancedDetermine.isBigInteger(-10));
console.log(advancedDetermine.isBigInteger(-10n, { positive: true }));
console.log(advancedDetermine.isBigInteger(7n, { negative: true, positive: true }));
console.log(advancedDetermine.isBigInteger(1024n, { positive: true }));
console.log(advancedDetermine.isBigInteger(1024n));
console.log(advancedDetermine.isBigInteger(NaN));
console.log(advancedDetermine.isFunction(() => {}));
console.log(advancedDetermine.isFunction(function* foo() {}, { generator: false }));
console.log(advancedDetermine.isJSON({ magic: () => { console.log("Test!") } }));
console.log(advancedDetermine.isJSON({ number: 1 }));
console.log(advancedDetermine.isJSON({}));
console.log(advancedDetermine.isMap(new Map([["a", 1], ["b", 2]])));
console.log(advancedDetermine.isNumber(-10, { positive: true }));
console.log(advancedDetermine.isNumber(-10));
console.log(advancedDetermine.isNumber(7.21, { float: true, integer: true }));
console.log(advancedDetermine.isNumber(8.31, { float: true, positive: true, safe: true }));
console.log(advancedDetermine.isNumber(1024, { positive: true }));
console.log(advancedDetermine.isNumber(1024));
console.log(advancedDetermine.isNumber(NaN));
console.log(advancedDetermine.isObject({ enable: false }));
console.log(advancedDetermine.isObject({ magic: () => { console.log("Test!") } }));
console.log(advancedDetermine.isObject(new Boolean(true)));
console.log(advancedDetermine.isObject(null));
console.log(advancedDetermine.isObject(true));
console.log(advancedDetermine.isPlainObject({ enable: false }));
console.log(advancedDetermine.isPlainObject({ magic: () => { console.log("Test!") } }));
console.log(advancedDetermine.isPlainObject(new Boolean(true)));
console.log(advancedDetermine.isPlainObject(null));
console.log(advancedDetermine.isPlainObject(true));
console.log(advancedDetermine.isRegularExpression(/ab+c/i));
console.log(advancedDetermine.isSet(new Set([1, 2, 3, 4, 5])));
console.log(advancedDetermine.isString("    ", { empty: false, preTrim: true }));
console.log(advancedDetermine.isString("    "));
console.log(advancedDetermine.isString("", { empty: false }));
console.log(advancedDetermine.isString(""));
console.log(advancedDetermine.isString("Hello World", { lowerCase: true }));
console.log(advancedDetermine.isString("Hello, world!", { lowerCase: true, upperCase: true }));
console.log(advancedDetermine.isString("Hello, world!"));
console.log(advancedDetermine.isString("null", { lowerCase: true }));
console.log(advancedDetermine.isString("null"));
console.log(advancedDetermine.isString(null));
console.log(advancedDetermine.isStringifyJSON("{ \"number\": 1 }"));
console.log(advancedDetermine.isStringifyJSON("{}"));
console.log(advancedDetermine.isStringifyJSON("word"));
console.log(advancedDetermine.typeOf("undefined"));
console.log(advancedDetermine.typeOf(undefined));
console.log(typeof [10, 20]);
console.log(advancedDetermine.typeOf([10, 20]));
console.log(advancedDetermine.typeOf([]));
