# $<Schema>$ https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: "Bug Report (Issue Form Field)"
description: "Report a bug."
labels:
  - "🐛bug"
  - "🔵unconfirm"
body:
  - type: "markdown"
    attributes:
      value: "> 🧪 **Experimental:** GitHub Issue Form is currently in beta; If encounter any issue(s), please use the original form."
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: "What the bug is?"
    validations:
      required: false
  - type: "checkboxes"
    id: "version"
    attributes:
      label: "Version"
      description: "What version(s) is affected? Must be a supported version(s) listed in the \"Security Policy\" (/.github/SECURITY.md)."
      options:
        - label: "5.0.2"
          required: false
        - label: "5.0.1"
          required: false
        - label: "5.0.0"
          required: false
    validations:
      required: false
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: "If this bug can be reproduce, please list your step(s)!"
    validations:
      required: false
  - type: "textarea"
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "What thing(s) should expected to happen?"
    validations:
      required: false
