# $<Schema>$ https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
name: "Bug Report (Issue Form Old)"
description: "Report a bug."
labels:
  - "🐛bug"
  - "🔵unconfirm"
body:
  - type: "markdown"
    attributes:
      value: |
        > ### Suggested Content List
        >
        > - **Describe:** What the bug is?
        > - **Version:** Must be a supported version(s) listed in the "Security Policy" (/.github/SECURITY.md).
        > - **To Reproduce:** If this bug can be reproduce, please list your step(s)!
        > - **Expected Behavior:** What thing(s) should expected to happen?
  - type: "textarea"
    id: "content"
    attributes:
      label: "Content"
    validations:
      required: false
