# yaml-language-server: $schema=https://json.schemastore.org/github-issue-forms.json
name: "Bug Report"
description: "Report a bug."
labels:
  - "Status/Pending 🔵"
  - "Type/Bug 🐛"
body:
  - type: "textarea"
    id: "describe"
    attributes:
      label: "Describe"
      description: "What the bug is?"
    validations:
      required: false
  - type: "dropdown"
    id: "version"
    attributes:
      label: "Version"
      description: "What versions are affected? Versions must be listed as supported in the Security Policy (file: `SECURITY.md`)."
      multiple: true
      options:
        - "v12.0.2"
        - "v12.0.1"
        - "v12.0.0"
        - "v11.2.2"
        - "v11.2.1"
        - "v11.2.0"
        - "v11.1.2"
        - "v10.4.2"
    validations:
      required: false
  - type: "textarea"
    id: "reproduce"
    attributes:
      label: "To Reproduce"
      description: "If this bug can be reproduce, please list the steps!"
    validations:
      required: false
  - type: "textarea"
    id: "expected-behavior"
    attributes:
      label: "Expected Behavior"
      description: "What things should expected to happen?"
    validations:
      required: false
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: "If there have information that related to this issue but not suitable to the other fields, please list those at here."
    validations:
      required: false
