/*==================
[NodeJS] Advanced Determine - Core
	Language:
		NodeJS/14.15.0
==================*/
const typeListMap = {
	"arr": "array",
	"array": "array",
	"bigint": "biginteger",
	"biginteger": "biginteger",
	"bigintegernegative": "bigintegernegative",
	"bigintegerpositive": "bigintegerpositive",
	"bigintngt": "bigintegernegative",
	"bigintpst": "bigintegerpositive",
	"boolean": "boolean",
	"buf": "buffer",
	"buffer": "buffer",
	"dataview": "dataview",
	"date": "date",
	"json": "json",
	"map": "map",
	"nul": "null",
	"null": "null",
	"num": "number",
	"number": "number",
	"numberfloat": "numberfloat",
	"numberinteger": "numberinteger",
	"numbernegative": "numbernegative",
	"numbernegativefloat": "numbernegativefloat",
	"numbernegativeinteger": "numbernegativeinteger",
	"numbernegativesafefloat": "numbernegativesafefloat",
	"numbernegativesafeinteger": "numbernegativesafeinteger",
	"numberpositive": "numberpositive",
	"numberpositivefloat": "numberpositivefloat",
	"numberpositiveinteger": "numberpositiveinteger",
	"numberpositivesafefloat": "numberpositivesafefloat",
	"numberpositivesafeinteger": "numberpositivesafeinteger",
	"numbersafefloat": "numbersafefloat",
	"numbersafeinteger": "numbersafeinteger",
	"numflt": "numberfloat",
	"numint": "numberinteger",
	"numngt": "numbernegative",
	"numngtflt": "numbernegativefloat",
	"numngtint": "numbernegativeinteger",
	"numngtsflt": "numbernegativesafefloat",
	"numngtsint": "numbernegativesafeinteger",
	"numpst": "numberpositive",
	"numpstflt": "numberpositivefloat",
	"numpstint": "numberpositiveinteger",
	"numpstsflt": "numberpositivesafefloat",
	"numpstsint": "numberpositivesafeinteger",
	"numsflt": "numbersafefloat",
	"numsint": "numbersafeinteger",
	"obj": "object",
	"object": "object",
	"objectpair": "objectpair",
	"objectplain": "objectpair",
	"objpair": "objectpair",
	"objplain": "objectpair",
	"regex": "regularexpression",
	"regexp": "regularexpression",
	"regexr": "regularexpression",
	"regularexpression": "regularexpression",
	"set": "set",
	"str": "string",
	"strascii": "stringascii",
	"string": "string",
	"stringascii": "stringascii",
	"stringifiedjson": "stringifyjson",
	"stringifyjson": "stringifyjson",
	"stringlowercase": "stringlowercase",
	"stringml": "stringmultipleline",
	"stringmultiline": "stringmultipleline",
	"stringmultipleline": "stringmultipleline",
	"stringsingleline": "stringsingleline",
	"stringsl": "stringsingleline",
	"stringuppercase": "stringuppercase",
	"strjson": "stringifyjson",
	"strl": "stringlowercase",
	"strlc": "stringlowercase",
	"strml": "stringmultipleline",
	"strsl": "stringsingleline",
	"stru": "stringuppercase",
	"struc": "stringuppercase",
	"symbol": "symbol",
	"udf": "undefined",
	"undefined": "undefined",
	"weakmap": "weakmap",
	"weakset": "weakset"
};
module.exports = {
	typeListMap
};
