declare namespace _default {
    export { isArray };
    export { isBigInt };
    export { isBigInteger };
    export { isFunction };
    export { isGenerator };
    export { isJSON };
    export { isJSONStringified };
    export { isJSONStringify };
    export { isMap };
    export { isNumber };
    export { isObject };
    export { isObjectPlain };
    export { isPlainObject };
    export { isRegEx };
    export { isRegExp };
    export { isRegularExpression };
    export { isSet };
    export { isString };
    export { isStringifiedJSON };
    export { isStringifyJSON };
}
export default _default;
import { isArray } from "./array.js";
import { isBigInt } from "./big-integer.js";
import { isBigInteger } from "./big-integer.js";
import { isFunction } from "./function.js";
import { isGenerator } from "./generator.js";
import { isJSON } from "./json.js";
import { isJSONStringified } from "./stringify-json.js";
import { isJSONStringify } from "./stringify-json.js";
import { isMap } from "./map.js";
import { isNumber } from "./number.js";
import { isObject } from "./object.js";
import { isObjectPlain } from "./plain-object.js";
import { isPlainObject } from "./plain-object.js";
import { isRegEx } from "./regular-expression.js";
import { isRegExp } from "./regular-expression.js";
import { isRegularExpression } from "./regular-expression.js";
import { isSet } from "./set.js";
import { isString } from "./string.js";
import { isStringifiedJSON } from "./stringify-json.js";
import { isStringifyJSON } from "./stringify-json.js";
export { isArray, isBigInt, isBigInteger, isFunction, isGenerator, isJSON, isJSONStringified, isJSONStringify, isMap, isNumber, isObject, isObjectPlain, isPlainObject, isRegEx, isRegExp, isRegularExpression, isSet, isString, isStringifiedJSON, isStringifyJSON };
//# sourceMappingURL=is.d.ts.map