declare namespace _default {
    export { areEqual };
    export { ArrayItemFilter };
    export { BigIntegerItemFilter };
    export { BigIntItemFilter };
    export { FunctionItemFilter };
    export { GeneratorItemFilter };
    export { isArray };
    export { isArrayStrict };
    export { isArrayUnique };
    export { isBigInt };
    export { isBigInteger };
    export { isBigIntegerEven };
    export { isBigIntegerIntegralNumericType };
    export { isBigIntegerNegative };
    export { isBigIntegerOdd };
    export { isBigIntegerPositive };
    export { isBigIntegerPrime };
    export { isBigIntegerSafe };
    export { isFunction };
    export { isGenerator };
    export { isJSON };
    export { isJSONStringified };
    export { isJSONStringify };
    export { isMap };
    export { isNumber };
    export { isNumberEven };
    export { isNumberFloat };
    export { isNumberIntegralNumericType };
    export { isNumberNegative };
    export { isNumberOdd };
    export { isNumberPositive };
    export { isNumberPrime };
    export { isNumberSafe };
    export { isObject };
    export { isObjectPlain };
    export { isPlainObject };
    export { isRegEx };
    export { isRegExp };
    export { isRegularExpression };
    export { isSet };
    export { isString };
    export { isStringASCII };
    export { isStringifiedJSON };
    export { isStringifyJSON };
    export { isStringLowerCase };
    export { isStringMultipleLine };
    export { isStringSingleLine };
    export { isStringUpperCase };
    export { JSONItemFilter };
    export { JSONStringifiedItemFilter };
    export { JSONStringifyItemFilter };
    export { MapItemFilter };
    export { NumberItemFilter };
    export { ObjectItemFilter };
    export { ObjectPlainItemFilter };
    export { PlainObjectItemFilter };
    export { RegExItemFilter };
    export { RegExpItemFilter };
    export { RegularExpressionItemFilter };
    export { SetItemFilter };
    export { StringifiedJSONItemFilter };
    export { StringifyJSONItemFilter };
    export { StringItemFilter };
    export { typeOf };
}
export default _default;
import { areEqual } from "./are-equal.js";
import { ArrayItemFilter } from "./array.js";
import { BigIntegerItemFilter } from "./big-integer.js";
import { BigIntItemFilter } from "./big-integer.js";
import { FunctionItemFilter } from "./function.js";
import { GeneratorItemFilter } from "./generator.js";
import { isArray } from "./array.js";
import { isArrayStrict } from "./native/array.js";
import { isArrayUnique } from "./native/array.js";
import { isBigInt } from "./big-integer.js";
import { isBigInteger } from "./big-integer.js";
import { isBigIntegerEven } from "./native/big-integer.js";
import { isBigIntegerIntegralNumericType } from "./native/big-integer.js";
import { isBigIntegerNegative } from "./native/big-integer.js";
import { isBigIntegerOdd } from "./native/big-integer.js";
import { isBigIntegerPositive } from "./native/big-integer.js";
import { isBigIntegerPrime } from "./native/big-integer.js";
import { isBigIntegerSafe } from "./native/big-integer.js";
import { isFunction } from "./function.js";
import { isGenerator } from "./generator.js";
import { isJSON } from "./json.js";
import { isJSONStringified } from "./stringify-json.js";
import { isJSONStringify } from "./stringify-json.js";
import { isMap } from "./map.js";
import { isNumber } from "./number.js";
import { isNumberEven } from "./native/number.js";
import { isNumberFloat } from "./native/number.js";
import { isNumberIntegralNumericType } from "./native/number.js";
import { isNumberNegative } from "./native/number.js";
import { isNumberOdd } from "./native/number.js";
import { isNumberPositive } from "./native/number.js";
import { isNumberPrime } from "./native/number.js";
import { isNumberSafe } from "./native/number.js";
import { isObject } from "./object.js";
import { isObjectPlain } from "./plain-object.js";
import { isPlainObject } from "./plain-object.js";
import { isRegEx } from "./regular-expression.js";
import { isRegExp } from "./regular-expression.js";
import { isRegularExpression } from "./regular-expression.js";
import { isSet } from "./set.js";
import { isString } from "./string.js";
import { isStringASCII } from "./native/string.js";
import { isStringifiedJSON } from "./stringify-json.js";
import { isStringifyJSON } from "./stringify-json.js";
import { isStringLowerCase } from "./native/string.js";
import { isStringMultipleLine } from "./native/string.js";
import { isStringSingleLine } from "./native/string.js";
import { isStringUpperCase } from "./native/string.js";
import { JSONItemFilter } from "./json.js";
import { JSONStringifiedItemFilter } from "./stringify-json.js";
import { JSONStringifyItemFilter } from "./stringify-json.js";
import { MapItemFilter } from "./map.js";
import { NumberItemFilter } from "./number.js";
import { ObjectItemFilter } from "./object.js";
import { ObjectPlainItemFilter } from "./plain-object.js";
import { PlainObjectItemFilter } from "./plain-object.js";
import { RegExItemFilter } from "./regular-expression.js";
import { RegExpItemFilter } from "./regular-expression.js";
import { RegularExpressionItemFilter } from "./regular-expression.js";
import { SetItemFilter } from "./set.js";
import { StringifiedJSONItemFilter } from "./stringify-json.js";
import { StringifyJSONItemFilter } from "./stringify-json.js";
import { StringItemFilter } from "./string.js";
import { typeOf } from "./type-of.js";
export { areEqual, ArrayItemFilter, BigIntegerItemFilter, BigIntItemFilter, FunctionItemFilter, GeneratorItemFilter, isArray, isArrayStrict, isArrayUnique, isBigInt, isBigInteger, isBigIntegerEven, isBigIntegerIntegralNumericType, isBigIntegerNegative, isBigIntegerOdd, isBigIntegerPositive, isBigIntegerPrime, isBigIntegerSafe, isFunction, isGenerator, isJSON, isJSONStringified, isJSONStringify, isMap, isNumber, isNumberEven, isNumberFloat, isNumberIntegralNumericType, isNumberNegative, isNumberOdd, isNumberPositive, isNumberPrime, isNumberSafe, isObject, isObjectPlain, isPlainObject, isRegEx, isRegExp, isRegularExpression, isSet, isString, isStringASCII, isStringifiedJSON, isStringifyJSON, isStringLowerCase, isStringMultipleLine, isStringSingleLine, isStringUpperCase, JSONItemFilter, JSONStringifiedItemFilter, JSONStringifyItemFilter, MapItemFilter, NumberItemFilter, ObjectItemFilter, ObjectPlainItemFilter, PlainObjectItemFilter, RegExItemFilter, RegExpItemFilter, RegularExpressionItemFilter, SetItemFilter, StringifiedJSONItemFilter, StringifyJSONItemFilter, StringItemFilter, typeOf };
//# sourceMappingURL=main.d.ts.map