const isArray = require("./is-array.js"),
	isBigIntegerNegative = require("./is-big-integer-negative.js"),
	isBigIntegerPositive = require("./is-big-integer-positive.js"),
	isNumber = require("./is-number.js"),
	isNumberFloat = require("./is-number-float.js"),
	isNumberInteger = require("./is-number-integer.js"),
	isNumberNegative = require("./is-number-negative.js"),
	isNumberNegativeFloat = require("./is-number-negative-float.js"),
	isNumberNegativeInteger = require("./is-number-negative-integer.js"),
	isNumberNegativeSafeFloat = require("./is-number-negative-safe-float.js"),
	isNumberNegativeSafeInteger = require("./is-number-negative-safe-integer.js"),
	isNumberPositive = require("./is-number-positive.js"),
	isNumberPositiveFloat = require("./is-number-positive-float.js"),
	isNumberPositiveInteger = require("./is-number-positive-integer.js"),
	isNumberPositiveSafeFloat = require("./is-number-positive-safe-float.js"),
	isNumberPositiveSafeInteger = require("./is-number-positive-safe-integer.js"),
	isNumberSafeFloat = require("./is-number-safe-float.js"),
	isNumberSafeInteger = require("./is-number-safe-integer.js"),
	isObject = require("./is-object.js"),
	isObjectPair = require("./is-object-pair.js"),
	isString = require("./is-string.js"),
	isStringASCII = require("./is-string-ascii.js"),
	isStringifyJSON = require("./is-stringify-json.js"),
	isStringLowerCase = require("./is-string-lower-case.js"),
	isStringMultipleLine = require("./is-string-multiple-line.js"),
	isStringSingleLine = require("./is-string-single-line.js"),
	isStringUpperCase = require("./is-string-upper-case.js");
const version = 2;
module.exports = {
	areEqual: require("./are-equal.js"),
	isArr: isArray,
	isArray: isArray,
	isBigIntegerNegative: isBigIntegerNegative,
	isBigIntegerPositive: isBigIntegerPositive,
	isBigIntNgt: isBigIntegerNegative,
	isBigIntPst: isBigIntegerPositive,
	isDict: isObjectPair,
	isDictionary: isObjectPair,
	isFloat: isNumberFloat,
	isFlt: isNumberFloat,
	isInt: isNumberInteger,
	isInteger: isNumberInteger,
	isJSON: require("./is-json.js"),
	isList: isArray,
	isNum: isNumber,
	isNumber: isNumber,
	isNumberFloat: isNumberFloat,
	isNumberInteger: isNumberInteger,
	isNumberNegative: isNumberNegative,
	isNumberNegativeFloat: isNumberNegativeFloat,
	isNumberNegativeInteger: isNumberNegativeInteger,
	isNumberNegativeSafeFloat: isNumberNegativeSafeFloat,
	isNumberNegativeSafeInteger: isNumberNegativeSafeInteger,
	isNumberPositive: isNumberPositive,
	isNumberPositiveFloat: isNumberPositiveFloat,
	isNumberPositiveInteger: isNumberPositiveInteger,
	isNumberPositiveSafeFloat: isNumberPositiveSafeFloat,
	isNumberPositiveSafeInteger: isNumberPositiveSafeInteger,
	isNumberSafeFloat: isNumberSafeFloat,
	isNumberSafeInteger: isNumberSafeInteger,
	isNumFlt: isNumberFloat,
	isNumInt: isNumberInteger,
	isNumNgt: isNumberNegative,
	isNumNgtFlt: isNumberNegativeFloat,
	isNumNgtInt: isNumberNegativeInteger,
	isNumNgtSFlt: isNumberNegativeSafeFloat,
	isNumNgtSInt: isNumberNegativeSafeInteger,
	isNumPst: isNumberPositive,
	isNumPstFlt: isNumberPositiveFloat,
	isNumPstInt: isNumberPositiveInteger,
	isNumPstSFlt: isNumberPositiveSafeFloat,
	isNumPstSInt: isNumberPositiveSafeInteger,
	isNumSFlt: isNumberSafeFloat,
	isNumSInt: isNumberSafeInteger,
	isObj: isObject,
	isObject: isObject,
	isObjectPair: isObjectPair,
	isObjectPlain: isObjectPair,
	isObjPair: isObjectPair,
	isObjPlain: isObjectPair,
	isStr: isString,
	isStrASCII: isStringASCII,
	isString: isString,
	isStringASCII: isStringASCII,
	isStringifiedJSON: isStringifyJSON,
	isStringifyJSON: isStringifyJSON,
	isStringLowerCase: isStringLowerCase,
	isStringML: isStringMultipleLine,
	isStringMultiLine: isStringMultipleLine,
	isStringMultipleLine: isStringMultipleLine,
	isStringSingleLine: isStringSingleLine,
	isStringSL: isStringSingleLine,
	isStringUpperCase: isStringUpperCase,
	isStrJSON: isStringifyJSON,
	isStrL: isStringLowerCase,
	isStrLC: isStringLowerCase,
	isStrML: isStringMultipleLine,
	isStrSL: isStringSingleLine,
	isStrU: isStringUpperCase,
	isStrUC: isStringUpperCase,
	typeOf: require("./type-of.js"),
	v: version,
	ver: version,
	version: version
};
