declare namespace _default {
    export { areEqual };
    export { isArray as isArr };
    export { isArray };
    export { isBigInteger as isBigInt };
    export { isBigInteger };
    export { isPlainObject as isDict };
    export { isPlainObject as isDictionary };
    export { isFunction as isFn };
    export { isFunction };
    export { isGenerator };
    export { isJSON };
    export { isStringifyJSON as isJSONStr };
    export { isStringifyJSON as isJSONStringified };
    export { isStringifyJSON as isJSONStringify };
    export { isArray as isList };
    export { isMap };
    export { $isNaN as isNaN };
    export { $isNaN as isNotANumber };
    export { isNumber as isNum };
    export { isNumber };
    export { isObject as isObj };
    export { isObject };
    export { isPlainObject as isObjectPlain };
    export { isPlainObject as isObjPlain };
    export { isPlainObject as isPlainObj };
    export { isPlainObject };
    export { isRegularExpression as isRegEx };
    export { isRegularExpression as isRegExp };
    export { isRegularExpression };
    export { isSet };
    export { isString as isStr };
    export { isString };
    export { isStringifyJSON as isStringifiedJSON };
    export { isStringifyJSON };
    export { isStringifyJSON as isStrJSON };
    export { typeOf };
}
export default _default;
import areEqual from "./are-equal.js";
import isArray from "./is-array.js";
import isBigInteger from "./is-big-integer.js";
import isPlainObject from "./is-plain-object.js";
import isFunction from "./is-function.js";
import isGenerator from "./is-generator.js";
import isJSON from "./is-json.js";
import isStringifyJSON from "./is-stringify-json.js";
import isMap from "./is-map.js";
declare const $isNaN: (number: unknown) => boolean;
import isNumber from "./is-number.js";
import isObject from "./is-object.js";
import isRegularExpression from "./is-regular-expression.js";
import isSet from "./is-set.js";
import isString from "./is-string.js";
import typeOf from "./type-of.js";
export { areEqual, isArray as isArr, isArray, isBigInteger as isBigInt, isBigInteger, isPlainObject as isDict, isPlainObject as isDictionary, isFunction as isFn, isFunction, isGenerator, isJSON, isStringifyJSON as isJSONStr, isStringifyJSON as isJSONStringified, isStringifyJSON as isJSONStringify, isArray as isList, isMap, $isNaN as isNaN, $isNaN as isNotANumber, isNumber as isNum, isNumber, isObject as isObj, isObject, isPlainObject as isObjectPlain, isPlainObject as isObjPlain, isPlainObject as isPlainObj, isPlainObject, isRegularExpression as isRegEx, isRegularExpression as isRegExp, isRegularExpression, isSet, isString as isStr, isString, isStringifyJSON as isStringifiedJSON, isStringifyJSON, isStringifyJSON as isStrJSON, typeOf };
//# sourceMappingURL=main.d.ts.map