declare namespace _default {
    export { isArrayStrict };
    export { isArrayUnique };
    export { isAsyncFunction };
    export { isAsyncGenerator };
    export { isAsyncGeneratorFunction };
    export { isAsynchronousFunction };
    export { isAsynchronousGenerator };
    export { isAsynchronousGeneratorFunction };
    export { isBigIntegerEven };
    export { isBigIntegerIntegralNumericType };
    export { isBigIntegerNegative };
    export { isBigIntegerOdd };
    export { isBigIntegerPositive };
    export { isBigIntegerPrime };
    export { isBigIntegerSafe };
    export { isBigIntEven };
    export { isBigIntIntegralNumericType };
    export { isBigIntNegative };
    export { isBigIntOdd };
    export { isBigIntPositive };
    export { isBigIntPrime };
    export { isBigIntSafe };
    export { isNumberEven };
    export { isNumberFloat };
    export { isNumberIntegralNumericType };
    export { isNumberNegative };
    export { isNumberOdd };
    export { isNumberPositive };
    export { isNumberPrime };
    export { isNumberSafe };
    export { isObjectPlain };
    export { isStringASCII };
    export { isStringLowerCase };
    export { isStringMultipleLine };
    export { isStringSingleLine };
    export { isStringUpperCase };
    export { isSyncFunction };
    export { isSyncGenerator };
    export { isSyncGeneratorFunction };
    export { isSynchronousFunction };
    export { isSynchronousGenerator };
    export { isSynchronousGeneratorFunction };
}
export default _default;
import { isArrayStrict } from "./native/array.js";
import { isArrayUnique } from "./native/array.js";
import { isAsyncFunction } from "./native/function.js";
import { isAsyncGenerator } from "./native/generator.js";
import { isAsyncGeneratorFunction } from "./native/function.js";
import { isAsynchronousFunction } from "./native/function.js";
import { isAsynchronousGenerator } from "./native/generator.js";
import { isAsynchronousGeneratorFunction } from "./native/function.js";
import { isBigIntegerEven } from "./native/big-integer.js";
import { isBigIntegerIntegralNumericType } from "./native/big-integer.js";
import { isBigIntegerNegative } from "./native/big-integer.js";
import { isBigIntegerOdd } from "./native/big-integer.js";
import { isBigIntegerPositive } from "./native/big-integer.js";
import { isBigIntegerPrime } from "./native/big-integer.js";
import { isBigIntegerSafe } from "./native/big-integer.js";
import { isBigIntEven } from "./native/big-integer.js";
import { isBigIntIntegralNumericType } from "./native/big-integer.js";
import { isBigIntNegative } from "./native/big-integer.js";
import { isBigIntOdd } from "./native/big-integer.js";
import { isBigIntPositive } from "./native/big-integer.js";
import { isBigIntPrime } from "./native/big-integer.js";
import { isBigIntSafe } from "./native/big-integer.js";
import { isNumberEven } from "./native/number.js";
import { isNumberFloat } from "./native/number.js";
import { isNumberIntegralNumericType } from "./native/number.js";
import { isNumberNegative } from "./native/number.js";
import { isNumberOdd } from "./native/number.js";
import { isNumberPositive } from "./native/number.js";
import { isNumberPrime } from "./native/number.js";
import { isNumberSafe } from "./native/number.js";
import { isObjectPlain } from "./native/plain-object.js";
import { isStringASCII } from "./native/string.js";
import { isStringLowerCase } from "./native/string.js";
import { isStringMultipleLine } from "./native/string.js";
import { isStringSingleLine } from "./native/string.js";
import { isStringUpperCase } from "./native/string.js";
import { isSyncFunction } from "./native/function.js";
import { isSyncGenerator } from "./native/generator.js";
import { isSyncGeneratorFunction } from "./native/function.js";
import { isSynchronousFunction } from "./native/function.js";
import { isSynchronousGenerator } from "./native/generator.js";
import { isSynchronousGeneratorFunction } from "./native/function.js";
export { isArrayStrict, isArrayUnique, isAsyncFunction, isAsyncGenerator, isAsyncGeneratorFunction, isAsynchronousFunction, isAsynchronousGenerator, isAsynchronousGeneratorFunction, isBigIntegerEven, isBigIntegerIntegralNumericType, isBigIntegerNegative, isBigIntegerOdd, isBigIntegerPositive, isBigIntegerPrime, isBigIntegerSafe, isBigIntEven, isBigIntIntegralNumericType, isBigIntNegative, isBigIntOdd, isBigIntPositive, isBigIntPrime, isBigIntSafe, isNumberEven, isNumberFloat, isNumberIntegralNumericType, isNumberNegative, isNumberOdd, isNumberPositive, isNumberPrime, isNumberSafe, isObjectPlain, isStringASCII, isStringLowerCase, isStringMultipleLine, isStringSingleLine, isStringUpperCase, isSyncFunction, isSyncGenerator, isSyncGeneratorFunction, isSynchronousFunction, isSynchronousGenerator, isSynchronousGeneratorFunction };
