name: "NodeJS Publish"
on:
  release:
    types:
      - "published"
jobs:
  publish-npm:
    name: "Publish To NPM"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.1.2"
        with:
          node-version: 12
          registry-url: "https://registry.npmjs.org/"
      - if: ${{github.event.release.prerelease == false}}
        name: "Publish To Tag @latest"
        run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
      - if: ${{github.event.release.prerelease == true}}
        name: "Publish To Tag @pre"
        run: "npm publish --tag pre"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
  # publish-gpr:
  #   name: "Publish To GitHub Package"
  #   runs-on: "ubuntu-latest"
  #   steps:
  #     - name: "Checkout Repository"
  #       uses: "actions/checkout@v2"
  #     - name: "Setup NodeJS"
  #       uses: "actions/setup-node@v2.1.2"
  #       with:
  #         node-version: 12
  #         registry-url: "https://npm.pkg.github.com/"
  #     - name: "Publish"
  #       run: "npm publish"
  #       env:
  #         NODE_AUTH_TOKEN: "${{secrets.GITHUB_TOKEN}}"
