# $<Schema>$ https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: "Publish - NPM"
on:
  release:
    types:
      - "published"
  workflow_dispatch:
jobs:
  publish-test:
    name: "Publish Test"
    runs-on: "ubuntu-latest"
    if: "${{github.event_name != 'release'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Test Name"
        id: "test-name"
        run: "echo '::set-output name=package-name::$(jq .name package.json)'"
        shell: "bash"
      - name: "Test Version"
        id: "test-version"
        run: "echo '::set-output name=package-version::$(jq .version package.json)'"
        shell: "bash"
      - name: "Test Conclusion"
        run: "echo ${{steps.test-name.outputs.package-name}}"
        shell: "bash"
      - name: "Test Conclusion 2"
        run: "echo ${{steps.test-version.outputs.package-version}}"
        shell: "bash"
  publish-npm:
    name: "Publish - NPM"
    runs-on: "ubuntu-latest"
    if: "${{github.event_name == 'release'}}"
    steps:
      - name: "Checkout Repository"
        uses: "actions/checkout@v2.3.4"
      - name: "Setup NodeJS"
        uses: "actions/setup-node@v2.4.1"
        with:
          node-version: 14
          check-latest: true
          registry-url: "https://registry.npmjs.org/"
      - name: "Publish To Tag @latest"
        if: ${{github.event.release.prerelease == false}}
        run: "npm publish"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
      - name: "Publish To Tag @pre"
        if: ${{github.event.release.prerelease == true}}
        run: "npm publish --tag pre"
        env:
          NODE_AUTH_TOKEN: "${{secrets.NPM_TOKEN}}"
